version: "3.8"

services:
  api:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/hungaro/
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: 
